Review
msharaf10/FC-Barcelona-BS pull request #1
Opened 2016-10-25 15:58 UTC by msharaf10

2016-10-27 04:26 UTC, shadyvb requested changes
Fix indentation, letter cases, in all files, and take care of the other comments.

2016-10-27 04:26 UTC, shadyvb commented on index.html
> +        <meta name="description" content="Official FC Barcelona website. All news about the team, ticket sales, member services, supporters club services and information about Barça and the Club">
Indent

2016-10-27 04:26 UTC, shadyvb commented on index.html
> +        <nav class="navbar navbar-default">
Indent

2016-10-27 04:26 UTC, shadyvb commented on index.html
> +                        <h2>club schedule</h2>
club > Club

2016-10-27 04:26 UTC, shadyvb commented on index.html
> +                <h1>FC Barcelona Get Straight Sack To Training</h1>
There shouldn't be too many H1 elements in a single page, typically a page should only have a single H1, a few H2's, and a bunch of H3's.

In H*x*, think of the *x* as the number of permitted occurrences of the heading type.

2016-10-27 04:26 UTC, shadyvb commented on index.html
> +                <h2>CAMP NOU EXPERIENCE</h2>
Capitalize via styling, HTML should have normal-cased letters.

2016-10-27 04:26 UTC, shadyvb commented on index.html
> +                <p class="lead">History happens here. Live it with the Tour & Museum.</p>
`&` should be written as `&amp;` in HTML, that's why GitHub highlights it in Red.

2016-10-27 04:26 UTC, shadyvb commented on index.html
> +                <div class="container-fluid img-responsive">                        <img src="images/campnou/19910958.jpg" alt="camp nou" class="img-responsive">
`img` tag should be on a new line.

2016-10-27 04:26 UTC, shadyvb commented on js/app.js
> +    $(".store-kit").on('click', '.get', function () {
Use single quotes unless you need otherwise.

2016-10-27 04:26 UTC, shadyvb commented on js/app.js
> +            price = $('<p class="price center-block">' + amount + '</p>'),
If you're creating new elements, construct them in jQuery, not by writing HTML directly. This protects you from XSS injection problems ( a hacking method ).

Example:
`$( '<p/>', { class: 'price center-block' } )` and `$( '<a/>', { href: 'xxx', class: 'xxx' } ).text( 'Buy now' )`

2016-10-29 23:17 UTC, msharafjr commented on js/app.js
> +            price = $('<p class="price center-block">' + amount + '</p>'),
Done

2016-10-29 23:17 UTC, msharaf10 commented on js/app.js
> +    $(".store-kit").on('click', '.get', function () {
'Done'

2016-10-29 23:18 UTC, msharaf10 commented on index.html
> +                <div class="container-fluid img-responsive">                        <img src="images/campnou/19910958.jpg" alt="camp nou" class="img-responsive">
eh eli wadda el tag da henak?! :smile: 
Done

2016-10-29 23:18 UTC, msharaf10 commented on index.html
> +                <p class="lead">History happens here. Live it with the Tour & Museum.</p>
Done

2016-10-29 23:18 UTC, msharafjr commented on index.html
> +                <h2>CAMP NOU EXPERIENCE</h2>
Done

2016-10-29 23:18 UTC, msharaf10 commented on index.html
> +                <h1>FC Barcelona Get Straight Sack To Training</h1>
Done

2016-10-29 23:18 UTC, msharaf10 commented on index.html
> +                        <h2>club schedule</h2>
Done

2016-10-29 23:18 UTC, msharaf10 commented on index.html
> +        <nav class="navbar navbar-default">
Done

2016-10-29 23:18 UTC, msharaf10 commented on index.html
> +        <meta name="description" content="Official FC Barcelona website. All news about the team, ticket sales, member services, supporters club services and information about Barça and the Club">
Done

2016-11-04 11:06 UTC, merged